version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-es6-sample
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
