version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-es6-sample
hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 300
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
